### ISSUE TITLE
send on closed channel when websocket is closed and reopened

### ISSUE THREAD

**Issue by SchiffFlieger** [SchiffFlieger/factorio-backend#9]
panic: send on closed channel

goroutine 85 [running]:
factorio-backend/logic.(*BasicChart).init(0xc0422225a0)
	D:/Workspace/Go/src/factorio-backend/logic/chart.go:61 +0x1ec
created by factorio-backend/logic.NewBasicChart
	D:/Workspace/Go/src/factorio-backend/logic/chart.go:24 +0x12d

**Comment by SchiffFlieger** [comment]
panic: send on closed channel

goroutine 317 [running]:
factorio-backend/logic.(*BasicChart).updateCycle(0xc042273980)
	C:/Users/koehler-laptop/Desktop/User/Workspace/Golang/src/factorio-backend/logic/chart.go:88 +0x2d9
factorio-backend/logic.(*BasicChart).(factorio-backend/logic.updateCycle)-fm()
	C:/Users/koehler-laptop/Desktop/User/Workspace/Golang/src/factorio-backend/logic/chart.go:73 +0x31
created by time.goFunc
	C:/Program Files/Golang/src/time/sleep.go:170 +0x4b
